@startuml
!include <C4/C4_Container>

Person(customer, "Customer")
Person(provider, "Provider")

System_Boundary(c1, "Supplier system") {
    System_Ext(identity_system, "IdentityService", "Авторизация пользователей")
    Container(supp_app, "Supplier", "Software System", "Целевая система")
}


Rel(customer, identity_system, "Аутентификация, запрашивает JWT", "HTTP")
Rel(provider, identity_system, "Аутентификация, запрашивает JWT", "HTTP")

Rel(customer, supp_app, "Размещает заказы", "HTTP")
Rel(supp_app, customer, "Передает уведомления по заказам", "HTTP")
Rel(provider, supp_app, "Размещает предолжения", "HTTP")
Rel(supp_app, provider, "Передает уведомления по предожениям", "HTTP")

@enduml